#!/bin/bash

# Use the Unofficial Bash Strict Mode
set -o errexit
set -o nounset
set -o pipefail
IFS=$'\n\t'
. ~/bin/trap.bashlib

set +o verbose
set +o xtrace

function build() {
    local dir="${1:?}"
    
    pushd "$dir" >/dev/null
    CONTAINER_VERSION="$(git describe --tags --dirty)"  docker-compose build
    popd >/dev/null
}

declare start=$(date +%s) 

export CFG_GITHUB_EMAIL=''
export CFG_GITHUB_HUBOT_TOKEN=''
export CFG_GITHUB_JENKINS_EMAIL=''
export CFG_GITHUB_JENKINS_NAME=''
export CFG_GITHUB_JENKINS_TOKEN=''
export CFG_GITHUB_JENKINS_USER=''
export CFG_GITHUB_NAME=''
export CFG_GITHUB_TOKEN=''
export CFG_GITHUB_USER=''
export CFG_PASS=''
export CFG_SLACK_HUBOT_TOKEN=''
export CFG_USER=''

[ -z "${CBF_VERSION:-}" ] || unset CBF_VERSION
[ -z "${CONTAINER_TAG:-}" ] || unset CONTAINER_TAG

cd ~/support

CBF_VERSION=dev build base_container
build supervisord
build nginx_base
build php5
build php7
build openjdk8

build hubot
build jenkins
build kafka-broker
build kafka-manager
build kafka-zookeeper
build mysql
build nagios
build nginx
build phpadmin
build supervisord-monitor
build webdav
build zenphoto 

build alpinefull
build postgres
build openjre8
build perl.5-24-3
build perl-carton
build files-kafka
build files-librd
build gradle
#build jenkins-build-events
#build jira-fd-kafka
build movefiles


declare finish=$(date +%s)
declare -i elapsed=$(( finish - start ))

echo ''
echo ''
TZ='America/New_York' date
printf "Time elapsed: %02d:%02d:%02d\n"  $((elapsed / 3600)) $((elapsed % 3600 / 60)) $((elapsed % 60))  
