#!/bin/bash

declare -r TOOLS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"   
source "${TOOLS}/build.bashlib"

declare -a modules=(base_container \
                    perl.5-26-2 \
                    perl-carton \
                    files-kafka \
                    files-librd \
                    \ #jenkins-build-events
                    \ #jira-fd-kafka
                    movefiles )

cd "$TOOLS"
build.allContainers "${modules[@]}"
