container_os:
    - alpine
#    - i386-ubuntu
#    - ubuntu

environment:
    KAFKA_BOOTSTRAP_SERVERS: s3.ubuntu.home:9092,s7.ubuntu.home:9092,s8.ubuntu.home:9092

parent_branches:
    - main
    - v3.9.9
    - latest

skip_builds:
    - movefiles
    - cesi
    - hubot
    - jira-fd-kafka
    - jenkins-build-events
    - mysql
    - nginx_alt
    - supervisord-monitor
    - ticket-checker
    - gradle
    - php5
    - php7
    - kafka-manager
    - perl
    - perl-carton
    - postgresql
#    - python
#    - kafka-eagle

all:
    - base_container
    - openjdk
    - confluent
    - build_container
    - python
    - perl
    - perl-carton
    - jsonnet

alpine:
    - hubot
    - jenkins
    - kafka-eagle
    - kafka-manager
    - nagios
    - nginx-base
    - nginx-proxy
    - openjre
    - php5
    - php7
    - php8
    - phpmyadmin
    - postgresql
    - smee
    - supervisord
    - webdav
