#!/bin/bash

declare -r TOOLS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"   
source "${TOOLS}/build.bashlib"

declare -a modules=(base_container \
                    supervisord \
                    nginx_base \
                    php5 \
                    php7 \
                    openjdk8
                    hubot \
                    jenkins \
                    kafka-broker \
                    kafka-manager \
                    kafka-zookeeper \
                    mysql \
                    nagios \
                    nginx \
                    \ #nginx_alt
                    nodervisor \
                    phpadmin \
                    supervisord-monitor \
                    webdav \
                    zenphoto \
                    perl.5-26-2 \
                    perl-carton \
                    files-kafka \
                    files-librd \
                    \ #jenkins-build-events
                    \ #jira-fd-kafka
                    movefiles \
                    alpinefull \
                    postgres \
                    openjre8 \
                    gradle )

cd "$TOOLS"
build.allContainers "${modules[@]}"

