container_os:
    - alpine
#    - i386-ubuntu
#    - ubuntu 

environment:
    KAFKA_BOOTSTRAP_SERVERS: s3.ubuntu.home:9092,s4.ubuntu.home:9092,s8.ubuntu.home:9092

parent_branches:
    - master
    - v3.9
    - latest

skip_builds:
    - kafka-eagle
    - jira-fd-kafka
    - jenkins-build-events
    - mysql
    - nginx_alt
    - supervisord-monitor
    - ticket-checker
    - gradle
    - python
    - php5
