container_os:
    - alpine
#    - i386-ubuntu
#    - ubuntu 

environment:
    KAFKA_BOOTSTRAP_SERVERS: s3.ubuntu.home:9092,s4.ubuntu.home:9092,s8.ubuntu.home:9092

parent_branches:
    - master
    - v3.9.8
    - latest

skip_builds:
    - movefiles
    - cesi
    - jira-fd-kafka
    - jenkins-build-events
    - mysql
    - nginx_alt
    - supervisord-monitor
    - ticket-checker
    - gradle
#    - python
    - php5

all:
    - base_container
    - openjdk
    - confluent
    - build_container
    - python 
    - perl
    - perl-carton

alpine:
    - hubot
    - jenkins
    - kafka-eagle
    - kafka-manager
    - nagios
    - nginx-base
    - nginx-proxy
    - openjre
    - php5
    - php7
    - phpmyadmin
    - postgresql
    - smee
    - supervisord
    - webdav
