#!/bin/bash

declare -r TOOLS="$( cd "$( dirname "${BASH_SOURCE[0]}" )/libs" && pwd )"   
source "${TOOLS}/loadLibraries.sh"

#jira-fd-kafka
#jenkins-build-events
#nginx_alt

declare -a modules=(base_container
                    openjdk
                    perl )

cd "$TOOLS/.."
export OS=centos/
[ $# -gt 0 ] && modules=( "$@" )
build.allContainers "${modules[@]}"

