#!/bin/bash

declare -r TOOLS="$( cd "$( dirname "${BASH_SOURCE[0]}" )/libs" && pwd )"   
source "${TOOLS}/loadLibraries.sh"

#jira-fd-kafka
#jenkins-build-events
#nginx_alt

declare -a modules=(base_container
                    openjdk
                    kafka-broker
                    kafka-zookeeper )

# package versions
export JAVA_VERSION=1.8.0_181
export PERL_VERSION=5.26.2


cd "$TOOLS/.."
export OS=i386-ubuntu/
[ $# -gt 0 ] && modules=( "$@" )
build.allContainers "${modules[@]}"

