#!/bin/bash

declare -r TOOLS="$( cd "$( dirname "${BASH_SOURCE[0]}" )/libs" && pwd )"   
source "${TOOLS}/loadLibraries.sh"

#jira-fd-kafka
#jenkins-build-events
#nginx_alt

declare -a modules=(base_container
                    supervisord
                    cesi
                    nginx-base
                    php5
                    php7
                    openjdk
                    hubot
                    jenkins
                    kafka-broker
                    kafka-manager
                    kafka-zookeeper
                    mysql
                    nagios
                    nginx-proxy
                    phpmyadmin
                    webdav
                    zenphoto
                    perl
                    perl-carton
                    files-kafka
                    files-librd
                    movefiles
                    alpinefull
                    postgresql
                    openjre
                    gradle
                    nodervisor
                    supervisord-monitor )

# package versions
export CESI_VERSION=2_api
export GRADLE_VERSION=4.9
export JENKINS_VERSION=2.138.1
export KAFKA_VERSION=2.0.0
export KM_VERSION=1.3.3.18
export MYSQL_VERSION=8.0.11
export NCORE_VERSION=4.4.2
export NOBJECT_VERSION=0.21.20
export NCONF_VERSION=1.3.0-0
export NGRAPH_VERSION=1.5.2
export NGINX_VERSION=1.15.4
export JAVA_VERSION=8.171.11-r0
export PERL_VERSION=5.26.2
export CPANIMUS_VERSION=1.7044
export PHP5_VERSION=5.6.37-r0
export PHP7_VERSION=7.2.8-r1
export PHPMYADMIN_VERSION=4.8.3
export POSTGRES_VERSION=10.5
export QUANTILE_VERSION=1.1.2
export TIMESCALEDB_VERSION=0.11.0
export SMONITOR_VERSION=v1.1.0
export ZOOKEEPER_VERSION=3.4.13


cd "$TOOLS/.."
[ $# -gt 0 ] && modules=( "$@" )
export OS=alpine/
build.allContainers "${modules[@]}"

