#!/bin/bash

# Use the Unofficial Bash Strict Mode
set -o errexit
set -o nounset
set -o pipefail
IFS=$'\n\t'
 
declare -r TOOLS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"   
[ -e ~/bin/trap.bashlib ] && source ~/bin/trap.bashlib
source "${TOOLS}/build.bashlib"


cd "$TOOLS"
set -x
registry.deleteImage phpadmin 39a3f99e0033474a33a69fa6d978ee9fa63ecaefe9e3dc76537df35596cd922a
registry.deleteImage phpadmin latest
set +x
