version: '3.5'

services:
    alpinefull:
        build:
            args:
                CODE_VERSION: base_container:20180210
            cache_from:
                - base_container:20180210
                - alpine:3.6
            context: ./alpinefull
        container_name: alpinefull
        depends_on:
            - base
        image: alpinefull:20180210
#        hostname: alpinefull
#        logging:
#            driver: "json-file"
#            options:
#                max-size: "10m"
#        volumes:
#                - ./alpinefull/vols-rw/opt:/opt

    base:
        build:
            args:
                CODE_VERSION: alpine:3.6
                TZ: "America/New_York"
            cache_from:
                - alpine:3.6
            context: ./base_container
        image: base_container:20180210

    carton:
        build:
            args:
                CODE_VERSION: perl-5.24.3:20180210
            cache_from:
                - perl-5.24.3:20180210
                - base_container:20180210
                - alpine:3.6
            context: ./perl-carton
        depends_on:
            - perl
        image: perl-carton:20180210

    files-librd:
        build:
            args:
                CODE_VERSION: perl-carton:20180210
            cache_from:
                - perl-carton:20180210
                - perl-5.24.3:20180210
                - base_container:20180210
                - alpine:3.6
            context: ./files-librd
        depends_on:
            - carton
        hostname: files-librd
        image: files-librd:20180210
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
        volumes:
           - ./files-librd:/usr/src/myapp
           - ./files-librd:/opt

    files-kafka:
        build:
            args:
                CODE_VERSION: perl-carton:20180210
            cache_from:
                - perl-carton:20180210
                - perl-5.24.3:20180210
                - base_container:20180210
                - alpine:3.6
            context: ./files-kafka
        depends_on:
            - carton
        hostname: files-kafka
        image: files-kafka:20180210
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3" 
        restart: unless-stopped
        volumes:
           - ./files-kafka:/usr/src/myapp
           - ./files-kafka:/opt

    gradle:
        build:
            args:
                CODE_VERSION: openjdk_8u131.11-r2:20180210
            cache_from:
                - openjdk_8u131.11-r2:20180210
                - base_container:20180210
                - alpine:3.6
            context: ./gradle
        depends_on:
            - openjdk
        image: gradle_4.4.1-jdk8-alpine:20180210

    movefiles:
        build:
            args:
                CODE_VERSION: perl-carton:20180210
            cache_from:
                - perl-carton:20180210
                - perl-5.24.3:20180210
                - base_container:20180210
                - alpine:3.6
            context: ./movefiles
        depends_on:
            - carton
        hostname: movefiles
        image: movefiles:20180210
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3" 
        restart: unless-stopped
        volumes:
            - ./movefiles:/usr/src/myapp

    openjdk:
        build:
            args:
                CODE_VERSION: base_container:20180210
            cache_from:
                - base_container:20180210
                - alpine:3.6
            context: ./openjdk8
        depends_on:
            - base
        image: openjdk_8u131.11-r2:20180210 

    openjre:
        build:
            args:
                CODE_VERSION: base_container:20180210
            cache_from:
                - base_container:20180210
                - alpine:3.6
            context: ./openjre8
        depends_on:
            - base
        image: openjre_8u131.11-r2:20180210 

    perl:
        build:
            args:
                CODE_VERSION: base_container:20180210
            cache_from:
                - base_container:20180210
            context: ./perl.5-24-3
        depends_on:
            - base
        image: perl-5.24.3:20180210

    postgres:
        build:
            args:
                CODE_VERSION: base_container:20180210
            cache_from:
                - base_container:20180210
                - alpine:3.6
            context: ./postgres
        container_name: postgres
        depends_on:
            - base
        environment:
            POSTGRES_PASSWORD: postgres
        hostname: postgres
        image: postgresql-10.1:20180210
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        ports:
            - 5432:5432
        restart: unless-stopped
        volumes:
            - ./vols-ro/postgres-initdb:/docker-entrypoint-initdb.d
            - ./vols-rw/data:/var/lib/postgresql/data
            - ./vols-ro/etc:/etc/postgres
            - ./vols-rw/log:/var/log/postgres 
