version: '3.5'

services:
    alpinefull:
        build:
            args:
                CONTAINER_NAME: alpinefull
                CONTAINER_VERSION: 1.0.4
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180225
            cache_from:
                - base_container:20180225
                - alpine:3.6
            context: ./alpinefull
            dockerfile: Dockerfile
        container_name: alpinefull
        image: alpinefull:20180225

    base:
        build:
            args:
                CONTAINER_NAME: base_container
                CONTAINER_VERSION: 1.0.4
                DEBUG_TRACE: 0
                FROM_BASE: alpine:3.6
                TZ: "America/New_York"
            cache_from:
                - alpine:3.6
            context: ./base_container
            dockerfile: Dockerfile
        image: base_container:20180225

    carton:
        build:
            args:
                CONTAINER_NAME: perl-carton
                CONTAINER_VERSION: 1.0.4
                DEBUG_TRACE: 0
                FROM_BASE: perl-5.24.3:20180225
            cache_from:
                - perl-5.24.3:20180225
                - base_container:20180225
                - alpine:3.6
            context: ./perl-carton
            dockerfile: Dockerfile
        image: perl-carton:20180225

    files-librd:
        build:
            args:
                CONTAINER_NAME: files-librd
                CONTAINER_VERSION: 1.0.4
                DEBUG_TRACE: 0
                FROM_BASE: perl-carton:20180225
            cache_from:
                - perl-carton:20180225
                - perl-5.24.3:20180225
                - base_container:20180225
                - alpine:3.6
            context: ./files-librd
            dockerfile: Dockerfile
        hostname: files-librd
        image: files-librd:20180225
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
        volumes:
           - ./files-librd:/usr/src/myapp
           - ./files-librd:/opt

    files-kafka:
        build:
            args:
                CONTAINER_NAME: files-kafka
                CONTAINER_VERSION: 1.0.4
                DEBUG_TRACE: 0
                FROM_BASE: perl-carton:20180225
            cache_from:
                - perl-carton:20180225
                - perl-5.24.3:20180225
                - base_container:20180225
                - alpine:3.6
            context: ./files-kafka
            dockerfile: Dockerfile
        hostname: files-kafka
        image: files-kafka:20180225
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3" 
        restart: unless-stopped
        volumes:
           - ./files-kafka:/usr/src/myapp
           - ./files-kafka:/opt

    gradle:
        build:
            args:
                CONTAINER_NAME: gradle
                CONTAINER_VERSION: 1.0.4
                DEBUG_TRACE: 0
                FROM_BASE: openjdk_8u131.11-r2:20180225
            cache_from:
                - openjdk_8u131.11-r2:20180225
                - base_container:20180225
                - alpine:3.6
            dockerfile: Dockerfile
            context: ./gradle
        image: gradle_4.4.1-jdk8-alpine:20180225

    movefiles:
        build:
            args:
                CONTAINER_NAME: movefiles
                CONTAINER_VERSION: 1.0.4
                DEBUG_TRACE: 0
                FROM_BASE: perl-carton:20180225
            cache_from:
                - perl-carton:20180225
                - perl-5.24.3:20180225
                - base_container:20180225
                - alpine:3.6
            context: ./movefiles
            dockerfile: Dockerfile
        hostname: movefiles
        image: movefiles:20180225
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3" 
        restart: unless-stopped
        volumes:
            - ./movefiles:/usr/src/myapp

    openjdk:
        build:
            args:
                CONTAINER_NAME: openjdk_8u131.11-r2
                CONTAINER_VERSION: 1.0.4
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180225
            cache_from:
                - base_container:20180225
                - alpine:3.6
            context: ./openjdk8
            dockerfile: Dockerfile
        image: openjdk_8u131.11-r2:20180225 

    openjre:
        build:
            args:
                CONTAINER_NAME: openjre_8u131.11-r2
                CONTAINER_VERSION: 1.0.4
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180225
            cache_from:
                - base_container:20180225
                - alpine:3.6
            context: ./openjre8
        image: openjre_8u131.11-r2:20180225 

    perl:
        build:
            args:
                CONTAINER_NAME: perl-5.24.3
                CONTAINER_VERSION: 1.0.4
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180225
            cache_from:
                - base_container:20180225
            context: ./perl.5-24-3
            dockerfile: Dockerfile
        image: perl-5.24.3:20180225

    postgres:
        build:
            args:
                CONTAINER_NAME: postgres
                CONTAINER_VERSION: 1.0.4
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180225
            cache_from:
                - base_container:20180225
                - alpine:3.6
            context: ./postgres
            dockerfile: Dockerfile
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: postgres
        hostname: postgres
        image: postgresql-10.2:20180225
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        ports:
            - 5432:5432
        restart: unless-stopped
        volumes:
            - ./vols-ro/postgres-initdb:/docker-entrypoint-initdb.d
            - ./vols-rw/data:/var/lib/postgresql/data
            - ./vols-ro/etc:/etc/postgres
            - ./vols-rw/log:/var/log/postgres 
