version: '3.3'

services:
    nagios:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: nagios
                FROM_BASE: ${DOCKER_REGISTRY:-}${OS:-}php/5.6.37-r0:${BASE_TAG:-latest}
 #               FROM_BASE: ${DOCKER_REGISTRY:-}${OS:-}php/tmp:${BASE_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-}${OS:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}${OS:-}base_container:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}${OS:-}supervisord:${BASE_TAG:-latest}
                - ${DOCKER_REGISTRY:-}${OS:-}php/5.6.37-r0:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: nagios
        container_name: nagios
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            NAGIOS_GITHUB_CREDENTIALS: ${CFG_GITHUB_USER}:${CFG_GITHUB_TOKEN}
            NAGIOS_GITHUB_EMAIL: $CFG_GITHUB_EMAIL
            NAGIOS_GITHUB_NAME: $CFG_GITHUB_NAME
            NAGIOS_PASS: $CFG_PASS
            NAGIOS_USER: $CFG_USER
            NCONF_DBHOST: mysql
            NCONF_DBNAME: nconf
            NCONF_DBPASS: $CFG_PASS
            NCONF_DBUSER: $CFG_USER
#            PWD_PROTECTED: 'true'
            SUPERVISORD_PASS: $CFG_PASS
            SUPERVISORD_USER: $CFG_USER
#            USER_ID: $CFG_USER
#            USER_PASS: $CFG_PASS
        hostname: nagios
        image: ${DOCKER_REGISTRY:-}${OS:-}nagios/4.3.4:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 25:25
            - 8003:80
#        restart: unless-stopped
        user: '1000'
        volumes:
            - ./vols/archives:/usr/local/nagios/var/archives
            - ./vols/rrd:/usr/local/nagios/var/rrd
            - ./vols/config:/usr/local/nagios/share/nconf/output
            - ./vols/log:/var/log
