FROM perl:5.26

RUN cpanm Carton \
    && mkdir -p /usr/src/app \
    && mkdir -p /usr/src/myapp

ONBUILD COPY cpanfile /usr/src/app/
ONBUILD RUN cd /usr/src/app ; carton install ; cp -r local/lib/perl5/* /usr/local/lib/perl5/site_perl/$(perl -e 'print substr $^V,1;')/ ; rm -rf local

WORKDIR /usr/src/myapp
