version: '3.5'

services:
    alpinefull:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-v3.0}
                CONTAINER_NAME: alpinefull
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: base_container:${CONTAINER_TAG:-20180421}
            cache_from:
                - base_container:${CONTAINER_TAG:-20180421}
                - alpine:3.6
            context: ./alpinefull
            dockerfile: Dockerfile
        container_name: alpinefull
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: alpinefull:${CONTAINER_TAG:-20180421}

    base:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-v3.0}
                CONTAINER_NAME: base_container
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: alpine:3.6
                TZ: "America/New_York"
            cache_from:
                - alpine:3.6
            context: ./base_container
            dockerfile: Dockerfile
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: base_container:${CONTAINER_TAG:-20180421}

    carton:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-v3.0}
                CONTAINER_NAME: perl-carton
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: perl-5.24.3:${CONTAINER_TAG:-20180421}
            cache_from:
                - perl-5.24.3:${CONTAINER_TAG:-20180421}
                - base_container:${CONTAINER_TAG:-20180421}
                - alpine:3.6
            context: ./perl-carton
            dockerfile: Dockerfile
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: perl-carton:${CONTAINER_TAG:-20180421}

    files-librd:
        build:
            args:
                CONTAINER_NAME: files-librd
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: perl-carton:${CONTAINER_TAG:-20180421}
            cache_from:
                - perl-carton:${CONTAINER_TAG:-20180421}
                - perl-5.24.3:${CONTAINER_TAG:-20180421}
                - base_container:${CONTAINER_TAG:-20180421}
                - alpine:3.6
            context: ./files-librd
            dockerfile: Dockerfile
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        hostname: files-librd
        image: files-librd:${CONTAINER_TAG:-20180421}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        restart: unless-stopped
        volumes:
           - ./files-librd:/usr/src/myapp
           - ./files-librd:/opt

    files-kafka:
        build:
            args:
                CONTAINER_NAME: files-kafka
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: perl-carton:${CONTAINER_TAG:-20180421}
            cache_from:
                - perl-carton:${CONTAINER_TAG:-20180421}
                - perl-5.24.3:${CONTAINER_TAG:-20180421}
                - base_container:${CONTAINER_TAG:-20180421}
                - alpine:3.6
            context: ./files-kafka
            dockerfile: Dockerfile
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        hostname: files-kafka
        image: files-kafka:${CONTAINER_TAG:-20180421}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        restart: unless-stopped
        volumes:
           - ./files-kafka:/usr/src/myapp
           - ./files-kafka:/opt

    gradle:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-v3.0}
                CONTAINER_NAME: gradle
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: openjdk_8u131.11-r2:${CONTAINER_TAG:-20180421}
            cache_from:
                - openjdk_8u131.11-r2:${CONTAINER_TAG:-20180421}
                - base_container:${CONTAINER_TAG:-20180421}
                - alpine:3.6
            dockerfile: Dockerfile
            context: ./gradle
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: gradle_4.4.1-jdk8-alpine:${CONTAINER_TAG:-20180421}

    movefiles:
        build:
            args:
                CONTAINER_NAME: movefiles
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: perl-carton:${CONTAINER_TAG:-20180421}
            cache_from:
                - perl-carton:${CONTAINER_TAG:-20180421}
                - perl-5.24.3:${CONTAINER_TAG:-20180421}
                - base_container:${CONTAINER_TAG:-20180421}
                - alpine:3.6
            context: ./movefiles
            dockerfile: Dockerfile
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        hostname: movefiles
        image: movefiles:${CONTAINER_TAG:-20180421}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        restart: unless-stopped
        volumes:
            - ./movefiles:/usr/src/myapp

    nginx_base:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-dev}
                CONTAINER_NAME: nginx_base
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: supervisord:${CONTAINER_TAG:-20180421}
            cache_from:
                - alpine:3.6
                - base_container:${CONTAINER_TAG:-20180421}
                - supervisord:${CONTAINER_TAG:-20180421}
            context: ./nginx_base
            dockerfile: Dockerfile
        container_name: nginx_base
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS: ${CFG_PASS}
            SUPERVISORD_USER: ${CFG_USER} 
        hostname: nginx_base
        image: nginx_base:${CONTAINER_TAG:-20180421}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
           - 8101:80
           - 9101:9001
# only use when building a 'service container' # only use when building a 'service container'
#        restart: unless-stopped

    openjdk:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-v3.0}
                CONTAINER_NAME: openjdk_8u131.11-r2
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: base_container:${CONTAINER_TAG:-20180421}
            cache_from:
                - base_container:${CONTAINER_TAG:-20180421}
                - alpine:3.6
            context: ./openjdk8
            dockerfile: Dockerfile
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: openjdk_8u131.11-r2:${CONTAINER_TAG:-20180421} 

    openjre:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-v3.0}
                CONTAINER_NAME: openjre_8u131.11-r2
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: base_container:${CONTAINER_TAG:-20180421}
            cache_from:
                - base_container:${CONTAINER_TAG:-20180421}
                - alpine:3.6
            context: ./openjre8
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: openjre_8u131.11-r2:${CONTAINER_TAG:-20180421} 

    perl:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-v3.0}
                CONTAINER_NAME: perl-5.24.3
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: base_container:${CONTAINER_TAG:-20180421}
            cache_from:
                - base_container:${CONTAINER_TAG:-20180421}
            context: ./perl.5-24-3
            dockerfile: Dockerfile
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: perl-5.24.3:${CONTAINER_TAG:-20180421}

    php5:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-v3.0}
                CONTAINER_NAME: php5
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: nginx_base:${CONTAINER_TAG:-20180421}
            cache_from:
                - alpine:3.6
                - base_container:${CONTAINER_TAG:-20180421}
                - supervisord:${CONTAINER_TAG:-20180421}
                - nginx_base:${CONTAINER_TAG:-20180421}
            context: ./php5
            dockerfile: Dockerfile
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS: ${CFG_PASS}
            SUPERVISORD_USER: ${CFG_USER} 
        image: php5:${CONTAINER_TAG:-20180421}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
           - 8102:80
           - 9102:9001
# only use when building a 'service container' 
        restart: unless-stopped

    php7:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-dev}
                CONTAINER_NAME: php7
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: nginx_base:${CONTAINER_TAG:-20180421}
            cache_from:
                - alpine:3.6
                - base_container:${CONTAINER_TAG:-20180421}
                - supervisord:${CONTAINER_TAG:-20180421}
                - nginx_base:${CONTAINER_TAG:-20180421}
            context: ./php7
            dockerfile: Dockerfile
        container_name: php7
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS: ${CFG_PASS}
            SUPERVISORD_USER: ${CFG_USER} 
        hostname: php7
        image: php7:${CONTAINER_TAG:-20180421}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
           - 8103:80
           - 9103:9001
        restart: unless-stopped

    postgres:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-v3.0}
                CONTAINER_NAME: postgres
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: base_container:${CONTAINER_TAG:-20180421}
            cache_from:
                - base_container:${CONTAINER_TAG:-20180421}
                - alpine:3.6
            context: ./postgres
            dockerfile: Dockerfile
        container_name: postgres
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            POSTGRES_PASSWORD: postgres
        hostname: postgres
        image: postgresql-10.3:${CONTAINER_TAG:-20180421}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 5432:5432
        restart: unless-stopped
        volumes:
            - ./vols-ro/postgres-initdb:/docker-entrypoint-initdb.d
            - ./vols-rw/data:/var/lib/postgresql/data
            - ./vols-ro/etc:/etc/postgres
            - ./vols-rw/log:/var/log/postgres 

    supervisord:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-v3.0}
                CONTAINER_NAME: supervisord
                CONTAINER_VERSION: 1.0.8
                FROM_BASE: base_container:${CONTAINER_TAG:-20180421}
            cache_from:
                - base_container:${CONTAINER_TAG:-20180421}
                - alpine:3.6
            context: ./supervisord
            dockerfile: Dockerfile
        container_name: supervisord
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            SUPERVISORD_PASS: $CFG_PASS
            SUPERVISORD_USER: $CFG_USER
        hostname: supervisord
        image: supervisord:${CONTAINER_TAG:-20180421}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 5432:5432
        restart: unless-stopped
        volumes:
            - ./vols-rw/log:/var/log 
