#!/bin/bash

declare image=${1:?}

declare REGISTRY_SERVER=afeoscyc-mw.cec.lab.emc.com/devops

[ "$(docker image ls -q $image)" ] || docker pull "$image"
docker tag "$image" "${REGISTRY_SERVER}/${image##*/}"
docker rmi "$image"
docker push "${REGISTRY_SERVER}/${image##*/}"
docker rmi "${REGISTRY_SERVER}/${image##*/}"