#!/bin/bash -x

declare image=${1:?}

declare REGISTRRY_SERVER=ubuntu-s2:5000

docker pull "$image"
docker tag "$image" "${REGISTRRY_SERVER}/${image##*/}"
docker rmi "$image"
docker push "${REGISTRRY_SERVER}/${image##*/}"
docker rmi "${REGISTRRY_SERVER}/${image##*/}"