#!/bin/bash

# Use the Unofficial Bash Strict Mode
set -o errexit
set -o nounset
set -o pipefail
IFS=$'\n\t'
 
declare -r TOOLS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"   
[ -e ~/bin/trap.bashlib ] && source ~/bin/trap.bashlib
source "${TOOLS}/build.bashlib"


cd "$TOOLS"
build.push "$@"
