#!/bin/bash

declare fn=registry.reportCatalogAsJson
if [ "$(env | grep "BASH_FUNC_${fn}%%")" ]; then
    TOP=/opt
else
    declare TOP="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
    source "${TOP}/libs/loadLibraries.sh"
fi

"$fn" "$@"
